language: php

php: [5.4, 5.5, 5.6, 7.0]

env:
  - SYMFONY_FRAMEWORK_BUNDLE="2.3.*" DOCTRINE_COMMON="2.2.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.3.*" DOCTRINE_COMMON="2.3.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.3.*" DOCTRINE_COMMON="2.4.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.3.*" DOCTRINE_COMMON="2.5.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.4.*" DOCTRINE_COMMON="2.2.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.4.*" DOCTRINE_COMMON="2.3.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.4.*" DOCTRINE_COMMON="2.4.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.4.*" DOCTRINE_COMMON="2.5.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.5.*" DOCTRINE_COMMON="2.2.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.5.*" DOCTRINE_COMMON="2.3.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.5.*" DOCTRINE_COMMON="2.4.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.5.*" DOCTRINE_COMMON="2.5.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.6.*" DOCTRINE_COMMON="2.2.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.6.*" DOCTRINE_COMMON="2.3.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.6.*" DOCTRINE_COMMON="2.4.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.6.*" DOCTRINE_COMMON="2.5.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.7.*" DOCTRINE_COMMON="2.2.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.7.*" DOCTRINE_COMMON="2.3.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.7.*" DOCTRINE_COMMON="2.4.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.7.*" DOCTRINE_COMMON="2.5.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.8.*" DOCTRINE_COMMON="2.2.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.8.*" DOCTRINE_COMMON="2.3.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.8.*" DOCTRINE_COMMON="2.4.*"
  - SYMFONY_FRAMEWORK_BUNDLE="2.8.*" DOCTRINE_COMMON="2.5.*"

before_script:
  - composer selfupdate
  - composer install --prefer-source

install:
   - composer require symfony/framework-bundle:${SYMFONY_FRAMEWORK_BUNDLE} doctrine/common:${DOCTRINE_COMMON}

script:
  - ./vendor/bin/phpspec run --format=pretty
